ZO_CreateStringId('SI_KEYBINDINGS_CATEGORY_PATHFINDER', 'Pathfinder')
ZO_CreateStringId('SI_BINDING_NAME_PATHFINDER_TOGGLE_PATHS_MANAGER', 'Toggle paths manager')
ZO_CreateStringId('SI_BINDING_NAME_PATHFINDER_ADD_POINT', 'Add Point')
ZO_CreateStringId('SI_BINDING_NAME_PATHFINDER_REMOVE_CLOSEST_POINT', 'Remove Closest')

ZO_CreateStringId('SI_BINDING_NAME_PATHFINDER_SHOW_FIRST_POINT', 'Show First Point')
ZO_CreateStringId('SI_BINDING_NAME_PATHFINDER_SHOW_NEXT_POINT', 'Show Next Point')
ZO_CreateStringId('SI_BINDING_NAME_PATHFINDER_SHOW_CLOSEST_POINT', 'Show Closest Point')
